server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://20.0.0.100:3306/spider_2020?useSSL=FALSE&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: admin123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  configuration:
    map-underscore-to-camel-case: true

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
